services:
  - type: web
    name: go-api
    env: go
    plan: free
    buildCommand: go build -o app .
    startCommand: ./app
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
