services:
  - type: web
    name: go-api
    env: go
    plan: free
    buildCommand: go1.24 build -o server ./cmd
    startCommand: ./app
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
